import 'package:gifts_app/logic/product.dart';
import 'package:gifts_app/widgets/ads.dart';
import 'package:gifts_app/widgets/colors.dart';

class AppLists {
  static List categories = [
    ['assets/balloons_icon.png', 'بالونات'],
    ['assets/cake_icon.png', 'حلويات'],
    ['assets/gift_icon.png', 'هدايا'],
    ['assets/bouquet_icon.png', 'ورد'],
  ];

  static List<Product> productsList = [
    Product(name: 'بالون', price: 20.0, image: 'assets/images/ballon.png', category: 'بالونات', content: []),
    Product(name: 'بالون', price: 20.0, image: 'assets/images/balloon1.png', category: 'بالونات', content: []),
    Product(name: 'بالون', price: 20.0, image: 'assets/images/balloon2.png', category: 'بالونات', content: []),
    Product(name: 'بالون', price: 20.0, image: 'assets/images/balloon3.png', category: 'بالونات', content: []),
    Product(name: 'بالون', price: 20.0, image: 'assets/images/balloon4.png', category: 'بالونات', content: []),
    Product(name: 'بالون', price: 20.0, image: 'assets/images/balloon5.png', category: 'بالونات', content: []),
    Product(name: 'بالون', price: 20.0, image: 'assets/images/balloon7.png', category: 'بالونات', content: []),
    Product(name: 'بالون', price: 20.0, image: 'assets/images/balloon6.png', category: 'بالونات', content: []),
    Product(name: 'بالون', price: 20.0, image: 'assets/images/balloon8.png', category: 'بالونات', content: []),
    Product(name: 'بالون', price: 20.0, image: 'assets/images/balloon9.png', category: 'بالونات', content: []),
    Product(name: 'بالون', price: 20.0, image: 'assets/images/balloon10.png', category: 'بالونات', content: []),
    Product(name: 'بالون', price: 20.0, image: 'assets/images/balloon22.png', category: 'بالونات', content: []),
    Product(name: 'ورد', price: 20.0, image: 'assets/images/rose.png', category: 'ورد', content: []),
    Product(name: 'ورد', price: 20.0, image: 'assets/images/rose1.png', category: 'ورد', content: []),
    Product(name: 'ورد', price: 20.0, image: 'assets/images/rose2.png', category: 'ورد', content: []),
    Product(name: 'ورد', price: 20.0, image: 'assets/images/rose3.png', category: 'ورد', content: []),
    Product(name: 'ورد', price: 20.0, image: 'assets/images/rose4.png', category: 'ورد', content: []),
    Product(name: 'ورد', price: 20.0, image: 'assets/images/rose5.png', category: 'ورد', content: []),
    Product(name: 'ورد', price: 20.0, image: 'assets/images/rose6.png', category: 'ورد', content: []),
    Product(name: 'ورد', price: 20.0, image: 'assets/images/rose7.png', category: 'ورد', content: []),
    Product(name: 'ورد', price: 20.0, image: 'assets/images/rose8.png', category: 'ورد', content: []),
    Product(name: 'ورد', price: 20.0, image: 'assets/images/rose9.png', category: 'ورد', content: []),
    Product(name: 'ورد', price: 20.0, image: 'assets/images/rose10.png', category: 'ورد', content: []),
    Product(name: 'ورد', price: 20.0, image: 'assets/images/rose11.png', category: 'ورد', content: []),
    Product(name: 'ورد', price: 20.0, image: 'assets/images/rose12.png', category: 'ورد', content: []),
    Product(name: 'ورد', price: 20.0, image: 'assets/images/rose13.png', category: 'ورد', content: []),
    Product(name: 'ورد', price: 20.0, image: 'assets/images/rose14.png', category: 'ورد', content: []),
    Product(name: 'ورد', price: 20.0, image: 'assets/images/rose15.png', category: 'ورد', content: []),
    Product(name: 'ورد', price: 20.0, image: 'assets/images/rose16.png', category: 'ورد', content: []),
    Product(name: 'ورد', price: 20.0, image: 'assets/images/rose17.png', category: 'ورد', content: []),
    Product(name: 'ورد', price: 20.0, image: 'assets/images/rose18.png', category: 'ورد', content: []),
    Product(name: 'ورد', price: 20.0, image: 'assets/images/rose19.png', category: 'ورد', content: []),
    Product(name: 'ورد', price: 20.0, image: 'assets/images/rose20.png', category: 'ورد', content: []),
    Product(name: 'ورد', price: 20.0, image: 'assets/images/rose21.png', category: 'ورد', content: []),
    Product(name: 'ورد', price: 20.0, image: 'assets/images/rose22.png', category: 'ورد', content: []),
    Product(name: 'ورد', price: 20.0, image: 'assets/images/rose23.png', category: 'ورد', content: []),
    Product(name: 'هديه', price: 20.0, image: 'assets/images/gift.png', category: 'هدايا', content: []),
    Product(name: 'هديه', price: 20.0, image: 'assets/images/gift1.png', category: 'هدايا', content: []),
    Product(name: 'هديه', price: 20.0, image: 'assets/images/gift2.png', category: 'هدايا', content: []),
    Product(name: 'هديه', price: 20.0, image: 'assets/images/gift3.png', category: 'هدايا', content: []),
    Product(name: 'هديه', price: 20.0, image: 'assets/images/gift4.png', category: 'هدايا', content: []),
    Product(name: 'هديه', price: 20.0, image: 'assets/images/gift5.png', category: 'هدايا', content: []),
    Product(name: 'هديه', price: 20.0, image: 'assets/images/gift6.png', category: 'هدايا', content: []),
    Product(name: 'هديه', price: 20.0, image: 'assets/images/gift7.png', category: 'هدايا', content: []),
    Product(name: 'هديه', price: 20.0, image: 'assets/images/gift8.png', category: 'هدايا', content: []),
    Product(name: 'هديه', price: 20.0, image: 'assets/images/gift9.png', category: 'هدايا', content: []),
    Product(name: 'هديه', price: 20.0, image: 'assets/images/gift10.png', category: 'هدايا', content: []),
    Product(name: 'هديه', price: 20.0, image: 'assets/images/gift11.png', category: 'هدايا', content: []),
    Product(name: 'هديه', price: 20.0, image: 'assets/images/gift12.png', category: 'هدايا', content: []),
    Product(name: 'هديه', price: 20.0, image: 'assets/images/gift13.png', category: 'هدايا', content: []),
    Product(name: 'هديه', price: 20.0, image: 'assets/images/gift14.png', category: 'هدايا', content: []),
    Product(name: 'هديه', price: 20.0, image: 'assets/images/gift15.png', category: 'هدايا', content: []),
    Product(name: 'هديه', price: 20.0, image: 'assets/images/gift16.png', category: 'هدايا', content: []),
    Product(name: 'هديه', price: 20.0, image: 'assets/images/gift17.png', category: 'هدايا', content: []),
    Product(name: 'هديه', price: 20.0, image: 'assets/images/gift18.png', category: 'هدايا', content: []),
    Product(name: 'هديه', price: 20.0, image: 'assets/images/gift19.png', category: 'هدايا', content: []),
    Product(name: 'هديه', price: 20.0, image: 'assets/images/gift20.png', category: 'هدايا', content: []),
    Product(name: 'هديه', price: 20.0, image: 'assets/images/gift21.png', category: 'هدايا', content: []),
    Product(name: 'هديه', price: 20.0, image: 'assets/images/gift22.png', category: 'هدايا', content: []),
    Product(name: 'هديه', price: 20.0, image: 'assets/images/gift23.png', category: 'هدايا', content: []),
    Product(name: 'هديه', price: 20.0, image: 'assets/images/gift24.png', category: 'هدايا', content: []),
    Product(name: 'هديه', price: 20.0, image: 'assets/images/gift25.png', category: 'هدايا', content: []),
    Product(name: 'هديه', price: 20.0, image: 'assets/images/gift26.png', category: 'هدايا', content: []),
    Product(name: 'هديه', price: 20.0, image: 'assets/images/gift27.png', category: 'هدايا', content: []),
    Product(name: 'هديه', price: 20.0, image: 'assets/images/gift28.png', category: 'هدايا', content: []),
    Product(name: 'هديه', price: 20.0, image: 'assets/images/gift29.png', category: 'هدايا', content: []),
    Product(name: 'هديه', price: 20.0, image: 'assets/images/gift30.png', category: 'هدايا', content: []),
    Product(name: 'هديه', price: 20.0, image: 'assets/images/gift31.png', category: 'هدايا', content: []),
    Product(name: 'هديه', price: 20.0, image: 'assets/images/gift32.png', category: 'هدايا', content: []),
    Product(name: 'هديه', price: 20.0, image: 'assets/images/gift33.png', category: 'هدايا', content: []),
    Product(name: 'كيكه', price: 20.0, image: 'assets/images/cake.png', category: 'حلويات', content: []),
    Product(name: 'كيكه', price: 20.0, image: 'assets/images/cake1.png', category: 'حلويات', content: []),
    Product(name: 'كيكه', price: 20.0, image: 'assets/images/cake2.png', category: 'حلويات', content: []),
    Product(name: 'كيكه', price: 20.0, image: 'assets/images/cake3.png', category: 'حلويات', content: []),
    Product(name: 'كيكه', price: 20.0, image: 'assets/images/cake4.png', category: 'حلويات', content: []),
    Product(name: 'كيكه', price: 20.0, image: 'assets/images/cake5.png', category: 'حلويات', content: []),
    Product(name: 'كيكه', price: 20.0, image: 'assets/images/cake6.png', category: 'حلويات', content: []),
    Product(name: 'كيكه', price: 20.0, image: 'assets/images/cake7.png', category: 'حلويات', content: []),
    Product(name: 'شوكلاته', price: 20.0, image: 'assets/images/chocolate.png', category: 'حلويات', content: []),
    Product(name: 'شوكلاته', price: 20.0, image: 'assets/images/chocolate1.png', category: 'حلويات', content: []),
    Product(name: 'شوكلاته', price: 20.0, image: 'assets/images/chocolate2.png', category: 'حلويات', content: []),
    Product(name: 'شوكلاته', price: 20.0, image: 'assets/images/chocolate3.png', category: 'حلويات', content: []),
    Product(name: 'شوكلاته', price: 20.0, image: 'assets/images/chocolate4.png', category: 'حلويات', content: []),
    Product(name: 'شوكلاته', price: 20.0, image: 'assets/images/chocolate5.png', category: 'حلويات', content: []),
    Product(name: 'شوكلاته', price: 20.0, image: 'assets/images/chocolate6.png', category: 'حلويات', content: []),
    Product(name: 'شوكلاته', price: 20.0, image: 'assets/images/chocolate7.png', category: 'حلويات', content: []),
    Product(name: 'شوكلاته', price: 20.0, image: 'assets/images/chocolate8.png', category: 'حلويات', content: []),
    Product(name: 'شوكلاته', price: 20.0, image: 'assets/images/chocolate9.png', category: 'حلويات', content: []),
    Product(name: 'شوكلاته', price: 20.0, image: 'assets/images/chocolate10.png', category: 'حلويات', content: []),
    Product(name: 'شوكلاته', price: 20.0, image: 'assets/images/chocolate11.png', category: 'حلويات', content: []),
    Product(name: 'شوكلاته', price: 20.0, image: 'assets/images/chocolate12.png', category: 'حلويات', content: []),
    Product(name: 'شوكلاته', price: 20.0, image: 'assets/images/chocolate15.png', category: 'حلويات', content: []),

  ];

  static List<Ads> adsList = [
    Ads(title: 'احتفل بنهاية العام مع أحبائك', description: 'خصومات تصل إلى 70% على جميع الهدايا الموسمية', image: 'assets/bouquet_icon.png', buttonColor: mainColor,),
    Ads(title: 'شارك أجمل اللحظات مع أصدقائك', description: 'هدايا تبدأ من عشرين ريال فقط', image: 'assets/balloons_icon.png'),
    Ads(title: 'لا تفوّت الفرصة', description: 'خصومات حصرية على مختارات الهدايا حتى مساء الأحد', image: 'assets/cake_icon.png'),
  ];

  static List<Product> productInCart = [];


}